const KEY="sresthetic-data-v1";
let data=JSON.parse(localStorage.getItem(KEY)||'{"clients":[],"appointments":[],"tasks":[],"events":[],"expenses":[],"settings":{"name":"Sresthetic"}}');
let page=location.hash.slice(1)||"dashboard"; let selectedDate=new Date().toISOString().slice(0,10);
const $=s=>document.querySelector(s), id=()=>crypto.randomUUID(), money=n=>new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}).format(Number(n)||0);
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function go(p){page=p;location.hash=p;render()}
function toast(t){let x=document.createElement("div");x.className="toast";x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),1800)}
function nav(){return '<nav class="nav">'+[["dashboard","🏠","Oggi"],["agenda","📅","Agenda"],["clients","👩","Clienti"],["expenses","💶","Spese"],["settings","⚙️","Impostazioni"]].map(x=>'<button class="'+(page===x[0]?"active":"")+'" onclick="go(\''+x[0]+'\')"><span>'+x[1]+'</span>'+x[2]+"</button>").join("")+"</nav>"}
function shell(body){return '<header class="top"><div class="bar"><div><div class="brand">SRESTHETIC</div><div class="sub">Agenda personale + professionale</div></div><button class="primary" onclick="quick()">＋ Aggiungi</button></div>'+nav()+'</header><main class="content">'+body+"</main>"}
function appointmentRow(a){let c=data.clients.find(x=>x.id===a.clientId);return '<div class="row"><div><b>'+esc(a.time||"")+' · '+esc(c?.name||a.title||"Impegno")+'</b><div class="sub">'+esc(a.service||"Appuntamento")+(a.price?' · '+money(a.price):"")+'</div></div><div class="actions"><span class="pill">'+esc(a.status||"programmato")+'</span><button class="danger" onclick="removeItem(\'appointments\',\''+a.id+'\')">×</button></div></div>'}
function dashboard(){let t=new Date(),ds=t.toISOString().slice(0,10),m=t.getMonth(),y=t.getFullYear(),today=data.appointments.filter(a=>a.date===ds),inc=data.appointments.filter(a=>a.status==="completed"&&new Date(a.date).getMonth()===m&&new Date(a.date).getFullYear()===y).reduce((s,a)=>s+Number(a.price||0),0),sp=data.expenses.filter(a=>new Date(a.date).getMonth()===m&&new Date(a.date).getFullYear()===y).reduce((s,a)=>s+Number(a.amount||0),0),next=data.appointments.filter(a=>a.date>=ds&&a.status!=="cancelled").sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,4);return '<div class="hero"><div class="eyebrow">'+t.toLocaleDateString("it-IT",{weekday:"long",day:"numeric",month:"long"})+'</div><h1>Tutto quello che devi ricordare, in un solo posto.</h1><p>Clienti, appuntamenti, impegni personali, attività, spese e backup. I dati restano sul dispositivo.</p></div><div class="grid stats"><div class="card"><div class="muted">Oggi</div><div class="metric">'+today.length+'</div><div class="muted">appuntamenti</div></div><div class="card"><div class="muted">Incassi mese</div><div class="metric">'+money(inc)+'</div><div class="muted">completati</div></div><div class="card"><div class="muted">Spese mese</div><div class="metric">'+money(sp)+'</div></div><div class="card"><div class="muted">Clienti</div><div class="metric">'+data.clients.length+'</div></div></div><section class="section"><div class="head"><h2>Oggi</h2><button class="secondary" onclick="go(\'agenda\')">Apri agenda</button></div><div class="list">'+(today.length?today.sort((a,b)=>a.time.localeCompare(b.time)).map(appointmentRow).join(""):'<div class="card empty">Nessun appuntamento oggi.</div>')+'</div></section><section class="section"><div class="head"><h2>In arrivo</h2><button class="secondary" onclick="go(\'agenda\')">Vedi tutto</button></div><div class="list">'+(next.length?next.map(appointmentRow).join(""):'<div class="card empty">Agenda libera.</div>')+'</div></section>'}
function agenda(){let a=data.appointments.filter(x=>x.date===selectedDate).sort((x,y)=>x.time.localeCompare(y.time)),e=data.events.filter(x=>x.date===selectedDate),t=data.tasks.filter(x=>x.date===selectedDate&&!x.done);return '<div class="head"><div><div class="eyebrow">Agenda</div><h1 style="font-size:36px;margin:4px 0">Giornata</h1><div class="muted">'+new Date(selectedDate+"T12:00").toLocaleDateString("it-IT",{weekday:"long",day:"numeric",month:"long"})+'</div></div><button class="primary" onclick="openAppointment()">＋ Appuntamento</button></div><div class="card form"><label>Data</label><input type="date" value="'+selectedDate+'" onchange="selectedDate=this.value;render()"><div class="actions"><button class="secondary" onclick="openEvent()">Impegno personale</button><button class="secondary" onclick="openTask()">Attività</button></div></div><section class="section"><div class="list">'+a.map(appointmentRow).join("")+e.map(x=>'<div class="row"><div><b>🟣 '+esc(x.title)+'</b><div class="sub">'+esc(x.time||"Tutto il giorno")+' · personale</div></div><button class="danger" onclick="removeItem(\'events\',\''+x.id+'\')">Elimina</button></div>').join("")+t.map(x=>'<div class="row"><div><b>☑️ '+esc(x.title)+'</b><div class="sub">Attività</div></div><button class="secondary" onclick="finishTask(\''+x.id+'\')">Fatta</button></div>').join("")+(!a.length&&!e.length&&!t.length?'<div class="card empty">Nessun impegno per questa giornata.</div>':"")+'</div></section>'}
function clients(){return '<div class="head"><div><div class="eyebrow">Rubrica</div><h1 style="font-size:36px;margin:4px 0">Clienti</h1><div class="muted">'+data.clients.length+' clienti</div></div><button class="primary" onclick="openClient()">＋ Cliente</button></div><div class="list">'+(data.clients.length?data.clients.map(c=>'<div class="row"><div><b>'+esc(c.name)+'</b><div class="sub">'+esc(c.phone||"Nessun telefono")+(c.notes?' · '+esc(c.notes):"")+'</div></div><div class="actions"><button class="secondary" onclick="openAppointment(\''+c.id+'\')">Agenda</button><button class="danger" onclick="removeItem(\'clients\',\''+c.id+'\')">Elimina</button></div></div>').join(""):'<div class="card empty">Aggiungi la prima cliente.</div>')+'</div>'}
function expenses(){let total=data.expenses.reduce((s,x)=>s+Number(x.amount||0),0);return '<div class="head"><div><div class="eyebrow">Studio</div><h1 style="font-size:36px;margin:4px 0">Spese</h1><div class="muted">Totale registrato: '+money(total)+'</div></div><button class="primary" onclick="openExpense()">＋ Spesa</button></div><div class="list">'+(data.expenses.length?data.expenses.slice().reverse().map(x=>'<div class="row"><div><b>'+esc(x.description)+'</b><div class="sub">'+new Date(x.date+"T12:00").toLocaleDateString("it-IT")+'</div></div><div class="actions"><b>'+money(x.amount)+'</b><button class="danger" onclick="removeItem(\'expenses\',\''+x.id+'\')">×</button></div></div>').join(""):'<div class="card empty">Nessuna spesa registrata.</div>')+'</div>'}
function settings(){return '<div class="eyebrow">Impostazioni</div><h1 style="font-size:36px;margin:4px 0 20px">Sresthetic</h1><section class="card form"><label>Nome visualizzato</label><input id="studioName" value="'+esc(data.settings.name)+'"><button class="primary" onclick="saveSettings()">Salva</button></section><section class="section card"><h2>Backup dati</h2><p class="muted">Esporta una copia JSON e conservala in File/iCloud.</p><div class="actions"><button class="primary" onclick="backup()">Esporta backup</button><label class="secondary">Importa backup<input type="file" accept=".json,application/json" style="display:none" onchange="restore(this.files[0])"></label></div></section><section class="section card"><h2>Privacy</h2><p class="muted">Nessun account e nessun database remoto.</p></section>'}
function modal(title,form,action){let x=document.createElement("div");x.id="modal";x.style="position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:40;padding:18px;display:flex;align-items:center;justify-content:center";x.innerHTML='<div class="card" style="width:min(520px,100%);max-height:90dvh;overflow:auto"><div class="head"><h2>'+title+'</h2><button class="danger" onclick="closeModal()">Chiudi</button></div>'+form+'<div class="actions" style="margin-top:14px"><button class="secondary" onclick="closeModal()">Annulla</button><button class="primary" onclick="'+action+'">Salva</button></div></div>';document.body.append(x)}
function closeModal(){$("#modal")?.remove()}
function openAppointment(cid=""){modal("Nuovo appuntamento",'<div class="form"><label>Cliente</label><select id="fclient"><option value="">Seleziona</option>'+data.clients.map(c=>'<option value="'+c.id+'" '+(c.id===cid?"selected":"")+'>'+esc(c.name)+"</option>").join("")+'</select><div class="two"><div><label>Data</label><input id="fdate" type="date" value="'+selectedDate+'"></div><div><label>Ora</label><input id="ftime" type="time" value="09:00"></div></div><label>Servizio</label><input id="fservice" placeholder="Es. Manicure gel"><div class="two"><div><label>Prezzo (€)</label><input id="fprice" type="number" step=".01"></div><div><label>Stato</label><select id="fstatus"><option value="scheduled">Programmato</option><option value="completed">Completato</option><option value="cancelled">Annullato</option></select></div></div></div>","saveAppointment()")}
function saveAppointment(){let a={id:id(),clientId:$("#fclient").value,date:$("#fdate").value,time:$("#ftime").value,service:$("#fservice").value,price:Number($("#fprice").value||0),status:$("#fstatus").value};if(!a.date)return;data.appointments.push(a);save();closeModal();toast("Appuntamento salvato");render()}
function openClient(){modal("Nuova cliente",'<div class="form"><label>Nome e cognome</label><input id="cname"><label>Telefono</label><input id="cphone" type="tel"><label>Note</label><textarea id="cnotes" rows="3"></textarea></div>','saveClient()')}
function saveClient(){let n=$("#cname").value.trim();if(!n)return;data.clients.push({id:id(),name:n,phone:$("#cphone").value.trim(),notes:$("#cnotes").value.trim()});save();closeModal();render()}
function openEvent(){modal("Impegno personale",'<div class="form"><label>Titolo</label><input id="etitle"><div class="two"><div><label>Data</label><input id="edate" type="date" value="'+selectedDate+'"></div><div><label>Ora</label><input id="etime" type="time"></div></div></div>','saveEvent()')}
function saveEvent(){let n=$("#etitle").value.trim();if(!n)return;data.events.push({id:id(),title:n,date:$("#edate").value,time:$("#etime").value});save();closeModal();render()}
function openTask(){modal("Nuova attività",'<div class="form"><label>Attività</label><input id="ttitle"><label>Data</label><input id="tdate" type="date" value="'+selectedDate+'"></div>','saveTask()')}
function saveTask(){let n=$("#ttitle").value.trim();if(!n)return;data.tasks.push({id:id(),title:n,date:$("#tdate").value,done:false});save();closeModal();render()}
function finishTask(i){let x=data.tasks.find(x=>x.id===i);if(x)x.done=true;save();render()}
function openExpense(){modal("Nuova spesa",'<div class="form"><label>Descrizione</label><input id="edesc"><div class="two"><div><label>Importo (€)</label><input id="eamount" type="number" step=".01"></div><div><label>Data</label><input id="expdate" type="date" value="'+new Date().toISOString().slice(0,10)+'"></div></div></div>','saveExpense()')}
function saveExpense(){let n=$("#edesc").value.trim();if(!n)return;data.expenses.push({id:id(),description:n,amount:Number($("#eamount").value||0),date:$("#expdate").value});save();closeModal();render()}
function removeItem(type,i){data[type]=data[type].filter(x=>x.id!==i);save();render()}
function saveSettings(){data.settings.name=$("#studioName").value||"Sresthetic";save();toast("Salvato");render()}
function quick(){modal("Aggiungi",'<div class="actions"><button class="primary" onclick="closeModal();openAppointment()">Appuntamento</button><button class="secondary" onclick="closeModal();openEvent()">Impegno personale</button><button class="secondary" onclick="closeModal();openTask()">Attività</button><button class="secondary" onclick="closeModal();openExpense()">Spesa</button></div>',"closeModal()")}
function backup(){let b=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="sresthetic-backup-"+new Date().toISOString().slice(0,10)+".json";a.click()}
async function restore(f){if(!f)return;try{data=JSON.parse(await f.text());save();toast("Backup importato");render()}catch{toast("Backup non valido")}}
function render(){let body=page==="agenda"?agenda():page==="clients"?clients():page==="expenses"?expenses():page==="settings"?settings():dashboard();$("#app").innerHTML=shell(body)}
window.addEventListener("hashchange",()=>{page=location.hash.slice(1)||"dashboard";render()});render();